INSERT INTO genres (name) VALUES ('Антиутопия');
INSERT INTO genres (name) VALUES ('Вестерн');
INSERT INTO genres (name) VALUES ('Дарк Академия');
INSERT INTO genres (name) VALUES ('Детектив');
INSERT INTO genres (name) VALUES ('Исекай');
INSERT INTO genres (name) VALUES ('Историческая эпоха');
INSERT INTO genres (name) VALUES ('Киберпанк');
INSERT INTO genres (name) VALUES ('Комедия');
INSERT INTO genres (name) VALUES ('Магический реализм');
INSERT INTO genres (name) VALUES ('Мелодрама');
INSERT INTO genres (name) VALUES ('Мистика');
INSERT INTO genres (name) VALUES ('Научная фантастика');
INSERT INTO genres (name) VALUES ('Нуар');
INSERT INTO genres (name) VALUES ('Приключения');
INSERT INTO genres (name) VALUES ('Психология');
INSERT INTO genres (name) VALUES ('Романтика');
INSERT INTO genres (name) VALUES ('Сказка');
INSERT INTO genres (name) VALUES ('Стимпанк');
INSERT INTO genres (name) VALUES ('Трагедия');
INSERT INTO genres (name) VALUES ('Триллер');
INSERT INTO genres (name) VALUES ('Утопия');
INSERT INTO genres (name) VALUES ('Фантастика');
INSERT INTO genres (name) VALUES ('Фэнтези');
INSERT INTO genres (name) VALUES ('Хоррор');